import { useEffect, useState } from "react"
import { api } from "../../services/api"
import { StatCard } from "../../components/StatCard"
import type { Alert, User } from "../../services/types"
type Metrics = { alerts_considered: number; contact_rate: number; repurchase_rate: number; average_days_between_purchases?: number | null }
export function Dashboard({ user }: { user: User }) {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [metrics, setMetrics] = useState<Metrics | null>(null); const [users, setUsers] = useState<User[]>([])
  useEffect(() => { api<Alert[]>("/alerts/inbox").then(setAlerts).catch(() => {}); if (user.role !== "ASESOR") { api<Metrics>("/reports/metrics").then(setMetrics).catch(() => {}); if (user.role === "ADMIN") api<User[]>("/users").then(setUsers).catch(() => {}) } }, [user.role])
  const open = alerts.filter(a => ["PENDIENTE", "REPROGRAMADO", "SIN_RESPUESTA"].includes(a.status))
  return <><div className="page-title"><div><p className="eyebrow">{user.role === "ASESOR" ? "MI JORNADA" : "SUPERVISION"}</p><h1>Hola, {user.full_name.split(" ")[0]}</h1></div><p>{new Intl.DateTimeFormat("es-PE", { dateStyle: "full" }).format(new Date())}</p></div><section className="stats"><StatCard label="Alertas activas" value={open.length} /><StatCard label="Para hoy" value={alerts.filter(a => a.next_action_date === new Date().toISOString().slice(0, 10)).length} accent="orange" /><StatCard label="Atendidas" value={alerts.filter(a => a.attempts_count > 0).length} accent="green" /><StatCard label="Tasa de recompra" value={metrics ? `${Math.round(metrics.repurchase_rate * 100)}%` : "-"} accent="purple" /></section>{user.role !== "ASESOR" && <section className="dashboard-grid"><article className="panel"><h2>Tipificaciones de atención</h2><div className="bars"><i style={{ height: "74%" }} /><i style={{ height: "48%" }} /><i style={{ height: "61%" }} /><i style={{ height: "32%" }} /></div><small>Seguimiento &nbsp; Sin respuesta &nbsp; No interesado &nbsp; Otros</small></article><article className="panel"><h2>Ventas por recompra</h2><div className="ring"><b>{metrics ? `${Math.round(metrics.repurchase_rate * 100)}%` : "0%"}</b></div><p>Conversión de alertas atendidas</p></article><article className="panel advisors"><h2>Asesores</h2>{users.filter(x => x.role === "ASESOR").slice(0, 5).map(x => <p key={x.id}><span className="avatar">{x.full_name[0]}</span>{x.full_name}<small>{x.is_active ? "Activo" : "Inactivo"}</small></p>)}{!users.length && <p>La lista de asesores está disponible para administradores.</p>}</article></section>}<section className="panel"><h2>Próximos vencimientos</h2><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Estado</th><th>Intentos</th><th>Asignado</th></tr></thead><tbody>{alerts.slice(0, 7).map(a => <tr key={a.id}><td>{a.expected_repurchase_date}</td><td><span className="badge">{a.status.replaceAll("_", " ")}</span></td><td>{a.attempts_count}</td><td>{a.assigned_advisor_id ? "Asesor asignado" : "Sin asignar"}</td></tr>)}{!alerts.length && <tr><td colSpan={4}>No hay alertas activas.</td></tr>}</tbody></table></div></section></>
}
